import { Inter } from 'next/font/google'
import './globals.scss'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <nav className='navContainer'>
            <Link href='/home'>홈</Link>
            <Link href='/dog'>강아지</Link>
            <Link href='/cat'>고양이</Link>
          </nav>
            {children}
        </div>
      </body>
    </html>
  )
}
